/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SRouteImport } from './routes/s'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as DpIdRouteImport } from './routes/dp.$id'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SRoute = SRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const DpIdRoute = DpIdRouteImport.update({
  id: '/dp/$id',
  path: '/dp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/register': typeof RegisterRoute
  '/s': typeof SRoute
  '/signin': typeof SigninRoute
  '/wishlist': typeof WishlistRoute
  '/dp/$id': typeof DpIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/register': typeof RegisterRoute
  '/s': typeof SRoute
  '/signin': typeof SigninRoute
  '/wishlist': typeof WishlistRoute
  '/dp/$id': typeof DpIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/register': typeof RegisterRoute
  '/s': typeof SRoute
  '/signin': typeof SigninRoute
  '/wishlist': typeof WishlistRoute
  '/dp/$id': typeof DpIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/register'
    | '/s'
    | '/signin'
    | '/wishlist'
    | '/dp/$id'
    | '/orders/$id'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/register'
    | '/s'
    | '/signin'
    | '/wishlist'
    | '/dp/$id'
    | '/orders/$id'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/addresses'
    | '/cart'
    | '/checkout'
    | '/register'
    | '/s'
    | '/signin'
    | '/wishlist'
    | '/dp/$id'
    | '/orders/$id'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AddressesRoute: typeof AddressesRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  RegisterRoute: typeof RegisterRoute
  SRoute: typeof SRoute
  SigninRoute: typeof SigninRoute
  WishlistRoute: typeof WishlistRoute
  DpIdRoute: typeof DpIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s': {
      id: '/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dp/$id': {
      id: '/dp/$id'
      path: '/dp/$id'
      fullPath: '/dp/$id'
      preLoaderRoute: typeof DpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AddressesRoute: AddressesRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  RegisterRoute: RegisterRoute,
  SRoute: SRoute,
  SigninRoute: SigninRoute,
  WishlistRoute: WishlistRoute,
  DpIdRoute: DpIdRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
